[tool.poetry]
authors = ["Thomas J. Fan <thomasjpfan@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
flytekit = "^1.13.3"
polars = "^1.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
